services:
  server-1:
    build: .
    container_name: server-1
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    restart: unless-stopped
    labels:
      autoheal-service: true
    healthcheck:
        test: /usr/local/bin/healthcheck.sh || exit 1
        start_period: 1m30s
        interval: 15s
        timeout: 30s
        retries: 3
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512m
        reservations:
          cpus: '1.0'
          memory: 256M
    logging:
      driver: "json-file"
      options:
          max-size: "20m"
          max-file: "3"
    
  autoheal:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 256m
        reservations:
          cpus: '0.5'
          memory: 128M
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal-service
    image: willfarrell/autoheal:latest
    network_mode: none
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
          max-size: "20m"
          max-file: "3"